name: Deploy to GitHub Pages

on:
  push:
    # branches: ["main"]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to build (leave empty for head of branch)'
        required: false
        default: ''

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: |
          chmod +x ./build.sh
          bash ./build.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
